-- SDFish — SEED danh mục sản phẩm SDVICO chi tiết (2026-09-24). Sinh TỰ ĐỘNG từ
-- src/data/sdvico-showcase.ts bằng scripts/gen-product-seed.mjs — ĐỪNG sửa tay,
-- sửa nội dung ở file TS rồi chạy lại script.
--
-- Nguồn nội dung: tài liệu "Thong-tin-chi-tiet-san-pham-SDVICO.docx" (SDVICO).
-- Thêm cột `detail` (jsonb: models/maker/forWho/benefits/specs/variant) cho trang
-- Chi tiết; thay 6 seed cũ (0016) bằng 11 sản phẩm chi tiết + BỎ "Điện thoại
-- vệ tinh XT-Pro" (không có trong tài liệu). Idempotent: chạy lại refresh nội dung.
--
-- Xem docs/app-map/04-data-model.md.
-- ⚠️ KHÔNG tự apply lên prod — bước duyệt riêng (ref znzgugvfhgmiszqgjulk).

alter table public.product_listings
  add column if not exists detail jsonb;

-- Bỏ 6 seed cũ (1111-series, gồm XT-Pro). Admin tự thêm (uuid ngẫu nhiên) KHÔNG bị đụng.
delete from public.product_listings
where id in ('b6e1a1a0-1111-4a11-8a11-000000000001', 'b6e1a1a0-1111-4a11-8a11-000000000002', 'b6e1a1a0-1111-4a11-8a11-000000000003', 'b6e1a1a0-1111-4a11-8a11-000000000004', 'b6e1a1a0-1111-4a11-8a11-000000000005', 'b6e1a1a0-1111-4a11-8a11-000000000006');

-- 11 sản phẩm chi tiết từ tài liệu. do update = seed là nguồn, chạy lại refresh.
insert into public.product_listings
  (id, vendor_kind, title, category, description, features, detail, image_url, line, "group", sort_order)
values
  ('b6e1a1a0-2222-4a22-8a22-000000000001', 'sdvico', 'Máy lọc dầu diesel SF50 / SF300B', 'Máy lọc dầu diesel', 'Lọc cặn siêu nhỏ và tách nước, giữ kim phun và bơm cao áp luôn sạch',
   '["Lọc 1–10 micron, tách nước khỏi dầu","Vỏ inox 304 chịu muối biển, túi lọc thay được","Giảm tiêu hao nhiên liệu 5–10% (theo tài liệu SP)"]'::jsonb, '{"models":"SF50 bản cơ, SF300B bản bơm điện","maker":"Sản phẩm SDVICO. Kỹ thuật SDVICO lắp tận tàu, bảo hành trực tiếp","forWho":"Tàu vỏ gỗ, vỏ sắt hay nghẹt kim phun, máy nổ không êm vì dầu lẫn nước và cặn.","benefits":["Lọc cặn siêu nhỏ và tách nước, giữ kim phun và bơm cao áp luôn sạch.","Máy nổ êm hơn, đỡ hỏng vặt, giảm tiêu hao nhiên liệu 5 tới 10% theo tài liệu sản phẩm.","Vỏ inox 304 chịu muối biển, túi lọc thay được, dễ vệ sinh."],"specs":[{"label":"Cấu trúc","value":"Bồn inox 304 hai khối, túi lọc thay được"},{"label":"Độ lọc","value":"1 tới 10 micron"},{"label":"Lưu lượng","value":"Khoảng 200 lít/giờ"},{"label":"Bơm dầu","value":"Bơm điện SF300, 12 tới 13,8 V một chiều"},{"label":"Kích thước","value":"52 x 20 x 50 cm"},{"label":"Khối lượng","value":"15 kg"},{"label":"Bảo hành","value":"12 tháng"}],"variant":"Hai bản cùng cấu trúc (bồn inox hai khối, túi lọc, van xả khí, van xả cặn). Bản bơm điện SF300B có thêm bơm dầu để tăng áp đầu ra và tách khí trong dầu; bản cơ SF50 không có bơm, dầu tự chảy theo đường ống."}'::jsonb, '/sdvico/loc-dau.jpg', 'xu-ly-dau', 'co_dien', 0),
  ('b6e1a1a0-2222-4a22-8a22-000000000002', 'sdvico', 'Máy lọc nước biển SEA-40 / SEA250', 'Máy lọc nước biển', 'Lọc nước biển thành nước ngọt ngay trên tàu bằng màng RO',
   '["Công suất ~250 lít/giờ, tách muối 99,6%","Nước ra đạt chuẩn nước ăn uống WHO","Kỹ thuật SDVICO lắp tận tàu"]'::jsonb, '{"models":"SD-M250 bản cơ, SEA250 và SEA-40 bản điện","maker":"Sản phẩm SDVICO. Thiết kế và lắp ráp tại Việt Nam, kỹ thuật SDVICO lắp tận tàu","forWho":"Tàu đi biển dài ngày, chuyến nào cũng lo nước ngọt. Máy lọc nước biển thành nước ngọt ngay trên tàu bằng màng RO.","benefits":["Chủ động nước ngọt uống, nấu ăn, tắm rửa suốt chuyến biển.","Nước ra đạt chuẩn nước ăn uống của WHO.","Lấy nước biển sạch từ bơm làm mát máy tàu, kỹ thuật SDVICO lắp và hướng dẫn."],"specs":[{"label":"Công suất lọc","value":"Khoảng 250 lít/giờ, màng lọc 4040"},{"label":"Tách muối","value":"99,6%, nước ra dưới 500 ppm"},{"label":"Đầu bơm cao áp","value":"SEA250 loại 1525 đầu đỏ; SEA-40 loại 1111 đầu đen, áp thấp hơn"},{"label":"Cụm motor","value":"2,2 kW, 1 pha 220 V hoặc 3 pha 380 V"},{"label":"Kích thước","value":"150 x 50 x 80 cm"},{"label":"Khối lượng","value":"Khoảng 60 kg"},{"label":"Bảo hành","value":"12 tháng, cả màng RO, đầu bơm"}],"variant":"Hai bản cùng cấu trúc (màng RO, lõi lọc thô, bơm cao áp, đồng hồ áp suất). Bản điện SEA250/SEA-40 có cụm motor chạy điện tàu để kéo bơm cao áp; bản cơ SD-M250 không có cụm motor, không dùng điện."}'::jsonb, '/sdvico/sea40.jpg', 'loc-nuoc', 'co_dien', 1),
  ('b6e1a1a0-2222-4a22-8a22-000000000003', 'sdvico', 'Giám sát hành trình Viettel S-Tracking', 'Giám sát hành trình', 'Thiết bị giám sát hành trình tàu cá theo quy định để ra khơi hợp lệ',
   '["Định vị GPS, truyền qua di động và vệ tinh Iridium","Chống nước IP67","SDVICO lắp tận bến, hỗ trợ hồ sơ đăng ký"]'::jsonb, '{"models":"MTR-V02-VNM","maker":"SDVICO phân phối và lắp đặt. Thiết bị và phần mềm giám sát thuộc Viettel","forWho":"Tàu cá cần thiết bị giám sát hành trình theo quy định để ra khơi hợp lệ. SDVICO lắp đặt tận bến, hỗ trợ hồ sơ đăng ký và bảo hành.","benefits":["Định vị GPS chính xác, truyền dữ liệu qua mạng di động và vệ tinh.","Chống nước chuẩn IP67, phù hợp môi trường tàu cá ngoài biển.","Kết nối hạ tầng Viettel, phủ sóng tốt vùng biển Việt Nam.","Bảo hành máy 12 tháng, phụ kiện 6 tháng."],"specs":[{"label":"Hãng sản xuất","value":"Viettel"},{"label":"Model","value":"MTR-V02-VNM"},{"label":"Định vị","value":"GPS"},{"label":"Truyền dữ liệu","value":"Mạng di động và vệ tinh Iridium"},{"label":"Chống nước","value":"IP67"},{"label":"Bảo hành","value":"12 tháng máy, 6 tháng phụ kiện"}]}'::jsonb, '/sdvico/s-tracking.jpg', 'giam-sat', 'dien_tu', 2),
  ('b6e1a1a0-2222-4a22-8a22-000000000004', 'sdvico', 'Giám sát hành trình Vifish.24', 'Giám sát hành trình', 'Cảnh báo trước khi tới vùng cấm, nút khẩn cấp qua vệ tinh',
   '["Báo trước 1 hải lý khi gần vùng cấm","Nút khẩn cấp gửi tín hiệu về Đài duyên hải","Pin dự phòng chạy tiếp ~48 giờ khi mất điện"]'::jsonb, '{"models":"Vifish.24, ăng ten ST 6100 kèm hộp đấu nối","maker":"SDVICO phân phối và lắp đặt. Thiết bị của Công ty TNHH MTV Thông tin điện tử Hàng hải Việt Nam (Vishipel)","forWho":"Tàu đang dùng Vifish.18 muốn nâng cấp, hoặc tàu lắp mới. Nâng cấp chỉ thay hộp đấu nối, giữ ăng ten, thi công nhanh.","benefits":["Báo trước khi tàu tới gần vùng cấm, tránh vượt ranh giới.","Nút khẩn cấp gửi tín hiệu qua vệ tinh về Đài Thông tin duyên hải.","Pin dự phòng chạy tiếp khoảng 48 giờ khi tàu mất điện."],"specs":[{"label":"Nguồn điện","value":"9 tới 32 V một chiều"},{"label":"Pin dự phòng","value":"Lithium-ion 5.000 mAh"},{"label":"Ăng ten ST 6100","value":"12,6 x 12,6 x 4,9 cm, chuẩn IP67"},{"label":"Hộp đấu nối","value":"20 x 9 x 4,5 cm, chuẩn IP66"},{"label":"Định vị","value":"GPS, Glonass, Beidou, Galileo"},{"label":"Truyền vị trí","value":"Qua vệ tinh Inmarsat, 2 giờ một lần"},{"label":"Cảnh báo vùng cấm","value":"Trước 1 hải lý, còi hoặc đèn"},{"label":"Nút khẩn cấp","value":"Có, kèm nắp bảo vệ"}]}'::jsonb, '/sdvico/vifish.png', 'giam-sat', 'dien_tu', 3),
  ('b6e1a1a0-2222-4a22-8a22-000000000005', 'sdvico', 'Điện thoại vệ tinh Thuraya MarineStar', 'Liên lạc vệ tinh', 'Gọi điện qua vệ tinh ngay trên biển, có nút SOS riêng',
   '["Gọi thoại qua vệ tinh Thuraya, ổn định","Máy bàn có tay nghe, nút SOS trên máy","GPS tích hợp, SDVICO lắp ăng ten và đi dây"]'::jsonb, '{"models":"Thuraya MarineStar MNB-01, kèm ăng ten SPACE 42","maker":"SDVICO phân phối và lắp đặt. Thiết bị của Thuraya, dịch vụ vệ tinh do Thuraya cung cấp","forWho":"Tàu cá đi xa bờ, ra khỏi vùng sóng di động mà vẫn cần gọi về nhà, gọi chủ vựa hay báo tin khi gặp sự cố.","benefits":["Gọi điện qua vệ tinh ngay trên biển, chất lượng thoại ổn định.","Máy bàn có tay nghe quen tay như điện thoại ở nhà, nút SOS riêng trên máy.","GPS tích hợp, thiết bị làm cho môi trường hàng hải.","SDVICO lắp ăng ten, đi dây trên tàu và hướng dẫn sử dụng."],"specs":[{"label":"Hãng sản xuất","value":"Thuraya"},{"label":"Kiểu máy","value":"Điện thoại bàn có tay nghe, màn hình màu"},{"label":"Ăng ten","value":"Thuraya SPACE 42, hình chuông gắn ngoài"},{"label":"Liên lạc","value":"Thoại qua vệ tinh Thuraya"},{"label":"Định vị","value":"GPS tích hợp"},{"label":"Nút khẩn cấp","value":"Nút SOS trên máy"},{"label":"Trọn bộ","value":"Máy, ăng ten, cuộn cáp, SIM, sách hướng dẫn"}]}'::jsonb, '/sdvico/thuraya.jpg', 'dien-thoai-ve-tinh', 'dien_tu', 4),
  ('b6e1a1a0-2222-4a22-8a22-000000000006', 'sdvico', 'Dầu nhớt Nano Graphene PV Engine RMI', 'Dầu nhớt động cơ', 'Dầu nhớt Nano Graphene cho động cơ diesel máy thủy chạy dài ngày',
   '["SAE 15W-40 và 20W-50, API CI-4/SL","Phụ gia Nano Graphene bảo vệ động cơ (công bố PVOIL)","Kéo dài thời gian thay dầu, tiết kiệm nhiên liệu"]'::jsonb, '{"models":"PV Engine RMI, SAE 15W-40 và 20W-50","maker":"Sản phẩm đồng phát triển cùng Công ty Cổ phần Dầu nhờn PVOIL","forWho":"Động cơ diesel máy thủy, kể cả máy turbo tăng áp, chạy dài ngày trong điều kiện nặng. PVOIL định vị dòng này cho tàu thuyền và máy phát điện.","benefits":["Phụ gia Nano Graphene bảo vệ động cơ tốt hơn, theo công bố của PVOIL.","Kéo dài thời gian thay dầu, tiết kiệm nhiên liệu.","Hàng chính hãng, hóa đơn đầy đủ, SDVICO giao tận bến."],"specs":[{"label":"Cấp độ nhớt","value":"SAE 15W-40, SAE 20W-50"},{"label":"Cấp chất lượng","value":"API CI-4/SL"},{"label":"Tiêu chuẩn đạt","value":"ACEA E7; MB 229.1; Volvo VDS-3; Cummins CES 20078; MAN M 3275"},{"label":"Đóng gói","value":"Thùng 18 lít, phuy 209 lít"},{"label":"Bảo quản","value":"Nơi khô ráo, dưới 60 độ C"}]}'::jsonb, '/sdvico/nano-graphene.jpg', 'nhot', 'nhu_yeu_pham', 5),
  ('b6e1a1a0-2222-4a22-8a22-000000000007', 'sdvico', 'Phụ gia dầu diesel AdNANO', 'Phụ gia nhiên liệu', 'Một chai 1 lít pha được 8.000 lít dầu, cháy triệt để, bớt khói',
   '["1 lít pha được 8.000 lít dầu diesel","Nhũ hóa nano, cháy triệt để, giảm muội","Tiêu hao nhiên liệu giảm 5,47% (công bố NSX)"]'::jsonb, '{"models":"AdNANO Fuel Additive For Diesel, chai 1 lít","maker":"Sản phẩm đồng phát triển cùng Phòng Thí nghiệm trọng điểm Công nghệ lọc, hóa dầu","forWho":"Tàu chạy máy diesel muốn máy bốc hơn, bớt khói, bớt muội. Chỉ cần đổ thẳng vào dầu theo tỷ lệ pha, không phải lắp thêm gì.","benefits":["Một chai 1 lít pha được 8.000 lít dầu diesel.","Nhũ hóa nano giúp dầu hóa sương tốt hơn, cháy triệt để, giảm muội động cơ.","Phát triển từ đề tài khoa học cấp nhà nước mã ĐTĐL.CN-03/16.","Theo nhà sản xuất công bố: tiêu hao nhiên liệu giảm 5,47%, khói giảm 5,68%."],"specs":[{"label":"Tỷ lệ pha","value":"1:8000 theo thể tích"},{"label":"Công suất động cơ","value":"Tăng 2,6% (công bố NSX)"},{"label":"Phát thải CO","value":"Giảm 9,13% (công bố NSX)"},{"label":"Phát thải NOx","value":"Giảm 11,47% (công bố NSX)"},{"label":"Tiêu chuẩn","value":"TCCS 04:2018/PTNTĐ"},{"label":"Hạn dùng","value":"3 năm kể từ ngày sản xuất"},{"label":"Dùng cho","value":"Tàu thuyền, máy phát điện, máy công trình, ô tô"}]}'::jsonb, '/sdvico/adnano.png', 'phu-gia', 'nhu_yeu_pham', 6),
  ('b6e1a1a0-2222-4a22-8a22-000000000008', 'sdvico', 'Ắc quy tàu cá Globe WPM-220', 'Ắc quy tàu cá', 'Ắc quy 12V 220Ah nuôi thiết bị giám sát, định vị, bộ đàm suốt chuyến',
   '["12 V 220 Ah, dòng khởi động lạnh 1.150 A","Dự trữ 380 phút khi máy phát ngừng sạc","Chuyên dùng cho tàu thuyền và định vị GPS"]'::jsonb, '{"models":"Globe Marine Battery WPM-220, 12 V 220 Ah","maker":"Sản phẩm đồng phát triển cùng Công ty TNHH Lê Long Việt Nam","forWho":"Tàu cần nguồn điện ổn định cho thiết bị giám sát hành trình, định vị, bộ đàm. Mất nguồn là thiết bị mất tín hiệu.","benefits":["Chuyên dùng cho tàu thuyền và thiết bị định vị GPS, theo nhãn của hãng.","Dung lượng 220 Ah, đủ nuôi thiết bị giám sát hành trình, đèn, bộ đàm suốt chuyến.","Dòng khởi động lạnh 1.150 A, đề máy khỏe.","Dự trữ 380 phút khi máy phát ngừng sạc."],"specs":[{"label":"Điện áp","value":"12 V"},{"label":"Dung lượng","value":"220 Ah (20 giờ); 176 Ah (5 giờ)"},{"label":"Dòng khởi động lạnh","value":"1.150 A ở -17,8 độ C"},{"label":"Dự trữ","value":"380 phút ở dòng 25 A"},{"label":"Kích thước","value":"518 x 276 x 268 mm"},{"label":"Khối lượng","value":"Khoảng 37,2 kg"},{"label":"Vỏ bình","value":"Nhựa PP"}]}'::jsonb, '/sdvico/ac-quy.png', 'dien-lai', 'co_dien', 7),
  ('b6e1a1a0-2222-4a22-8a22-000000000009', 'sdvico', 'Sơn tàu biển PV Paint', 'Sơn tàu biển', 'Sơn tàu cá: chống hà, chống rỉ, sơn phủ ngoài — công nghệ Chugoku (Nhật)',
   '["Sơn Graphene Coating Peraphene chống mài mòn","Sơn chống hà tự mài bóng, không thiếc, đạt IMO","Đủ dòng cho tàu vỏ gỗ và vỏ sắt"]'::jsonb, '{"models":"Toàn bộ dòng sơn tàu cá PV Paint, gồm Graphene Coating Peraphene","maker":"Sản phẩm đồng phát triển cùng Công ty Cổ phần Sơn Dầu khí Việt Nam","forWho":"Tàu vỏ gỗ, vỏ sắt lên đà sơn lại: chống hà, chống rỉ, sơn phủ ngoài. PV Paint sản xuất theo công nghệ Chugoku Marine Paints (Nhật Bản).","benefits":["Sơn Graphene Coating Peraphene do PV Paint tự nghiên cứu: chống mài mòn, tăng tuổi thọ công trình.","Sơn chống hà tàu gỗ hiệu lực 6 tới 24 tháng; sơn alkyd bóng cao cho tàu gỗ.","Sơn chống hà tự mài bóng không chứa thiếc, đạt quy định IMO, giảm tiêu hao nhiên liệu."],"specs":[{"label":"Hãng sản xuất","value":"PV Paint, công nghệ Chugoku (Nhật Bản)"},{"label":"Nhãn sơn","value":"Chugoku CMP, Sơn Hải Phòng, PV Paint"},{"label":"Sơn Peraphene","value":"Graphene Coating, màu xanh và nâu"},{"label":"Sơn lót, chống rỉ","value":"Shop primer giàu kẽm; epoxy đa năng"},{"label":"Sơn két ballast","value":"CMP Nova, Clean Keep"},{"label":"Sơn chống hà","value":"Tự mài bóng, không thiếc, dừng đỗ 30 tới 45 ngày"},{"label":"Phạm vi phân phối","value":"Toàn bộ dòng sơn cho tàu cá vỏ gỗ và vỏ sắt"}]}'::jsonb, '/sdvico/pv-paint.png', 'son', 'nhu_yeu_pham', 8),
  ('b6e1a1a0-2222-4a22-8a22-000000000010', 'sdvico', 'Ứng dụng SDFish', 'Ứng dụng cho ngư dân', 'Thời tiết, đường đi, giá cá và chỗ bán ngay trên điện thoại',
   '["Ra khơi: bản đồ biển, dẫn đường, tin bão","Giao dịch: giá cá theo vùng, vựa thu mua","Tàu cá: giấy tờ, thiết bị đã lắp, gọi kỹ thuật"]'::jsonb, '{"models":"SDFish, dùng trên điện thoại","maker":"Sản phẩm SDVICO phát triển. Trung tâm kết nối cho chủ tàu và bạn thuyền","forWho":"Chủ tàu và thuyền trưởng muốn biết thời tiết, đường đi, giá cá và chỗ bán ngay trên điện thoại, trước và trong chuyến biển.","benefits":["Ra khơi: bản đồ biển, dẫn đường, thời tiết và tin bão, tính hải trình và dầu chạy.","Giao dịch: giá cá theo vùng, biểu đồ giá cá ngừ, danh sách vựa thu mua có số gọi thẳng.","Tàu cá: giấy tờ tàu, thiết bị đã lắp, gọi kỹ thuật SDVICO khi cần.","Cảnh báo bão sớm ngay trang chủ để tính đường về."],"specs":[{"label":"Nền tảng","value":"Điện thoại, mở được bằng trình duyệt"},{"label":"Tài khoản","value":"Đăng nhập bằng số điện thoại"},{"label":"Bản đồ và dẫn đường","value":"Có, kèm ranh giới vùng biển"},{"label":"Thời tiết, tin bão","value":"Có"},{"label":"Giá cá, vựa thu mua","value":"Có, theo vùng"},{"label":"Liên hệ","value":"0939 243 222"}]}'::jsonb, '/sdvico/sdfish.png', 'app', null, 9),
  ('b6e1a1a0-2222-4a22-8a22-000000000011', 'sdvico', 'Nhật ký khai thác điện tử Ngư dân 247', 'Nhật ký khai thác điện tử', 'Ghi nhật ký chuyến biển ngay trên điện thoại, không cần sóng ngoài biển',
   '["Bấm là xong: xuất bến, thả/thu lưới, cập bến","Chuyển cá sang ghe tải bằng quét mã QR","Không cần sóng, có sóng tự gửi lên"]'::jsonb, '{"models":"Ứng dụng Ngư dân 247, dùng trên điện thoại","maker":"Sản phẩm SDVICO phát triển. Ghi nhật ký chuyến biển ngay trên điện thoại, có trên CH Play và App Store","forWho":"Chủ tàu và thuyền trưởng ghe lưới, ghe tải cần ghi nhật ký khai thác và thu mua mỗi chuyến biển, không muốn ghi tay.","benefits":["Bấm là xong: xuất bến, thả lưới, thu lưới, khai sản lượng, cập bến. Tự ghi tọa độ và giờ.","Ghe lưới chuyển cá sang ghe tải bằng quét mã QR, số ký sang thẳng nhật ký thu mua.","Không cần sóng ngoài biển, app tự lưu, có sóng sẽ tự gửi lên."],"specs":[{"label":"Nền tảng","value":"Android trên CH Play, iPhone trên App Store"},{"label":"Tài khoản","value":"Mã tàu (biển số) và mật khẩu SDVICO cấp"},{"label":"Ghe lưới","value":"Xuất bến, thả và thu lưới, khai sản lượng, cập bến"},{"label":"Ghe tải","value":"Nhận cá từ ghe lưới qua mã QR, danh sách thu mua"},{"label":"Kết nối hai ghe","value":"Chung mạng WiFi của thiết bị SCONECT"},{"label":"Hỗ trợ","value":"0254 359 6868, sdvico.vn"}]}'::jsonb, '', 'app', null, 10)
on conflict (id) do update set
  vendor_kind = excluded.vendor_kind,
  title       = excluded.title,
  category    = excluded.category,
  description = excluded.description,
  features    = excluded.features,
  detail      = excluded.detail,
  image_url   = excluded.image_url,
  line        = excluded.line,
  "group"     = excluded."group",
  sort_order  = excluded.sort_order,
  updated_at  = now();
